name: bloc_base
description: "BLoC base project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  intl: ^0.19.0
  equatable: ^2.0.7
  pretty_dio_logger: ^1.4.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  go_router: ^14.6.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/
